# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info/patch_envelope.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19info/patch_envelope.proto\x12\x13org.lfedge.eve.info\"\x9b\x01\n\x12ZInfoPatchEnvelope\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12<\n\x05state\x18\x04 \x01(\x0e\x32-.org.lfedge.eve.info.EVE_PATCH_ENVELOPE_STATE\x12\x0c\n\x04size\x18\x05 \x01(\x04\x12\x0e\n\x06\x65rrors\x18\x06 \x03(\t\"\x9f\x01\n\x1cZInfoOpaqueAppInstanceStatus\x12\r\n\x05\x61ppId\x18\x01 \x01(\t\x12\x0f\n\x07\x61ppName\x18\x02 \x01(\t\x12I\n\x12opaqueStatusAction\x18\x03 \x01(\x0e\x32-.org.lfedge.eve.info.EVE_OPAQUE_STATUS_ACTION\x12\x14\n\x0copaqueStatus\x18\x04 \x01(\x0c\"u\n\x17ZInfoPatchEnvelopeUsage\x12\x19\n\x11patchApiCallCount\x18\x01 \x01(\x04\x12?\n\x0bpatchStatus\x18\x02 \x01(\x0b\x32*.org.lfedge.eve.info.ZInfoPatchEnvelopeApp\"O\n\x15ZInfoPatchEnvelopeApp\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x17\n\x0ftimesDownloaded\x18\x03 \x01(\x04*\xa1\x01\n\x18\x45VE_PATCH_ENVELOPE_STATE\x12\x10\n\x0cPATCH_UNKOWN\x10\x00\x12\x0f\n\x0bPATCH_ERROR\x10\x01\x12\x12\n\x0ePATCH_RECEIVED\x10\x02\x12\x15\n\x11PATCH_DOWNLOADING\x10\x03\x12\x14\n\x10PATCH_DOWNLOADED\x10\x04\x12\x0f\n\x0bPATCH_READY\x10\x05\x12\x10\n\x0cPATCH_ACTIVE\x10\x06*5\n\x18\x45VE_OPAQUE_STATUS_ACTION\x12\n\n\x06IGNORE\x10\x00\x12\r\n\tOVERWRITE\x10\x01\x42\x39\n\x13org.lfedge.eve.infoZ\"github.com/lf-edge/eve-api/go/infob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'info.patch_envelope_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023org.lfedge.eve.infoZ\"github.com/lf-edge/eve-api/go/info'
  _globals['_EVE_PATCH_ENVELOPE_STATE']._serialized_start=571
  _globals['_EVE_PATCH_ENVELOPE_STATE']._serialized_end=732
  _globals['_EVE_OPAQUE_STATUS_ACTION']._serialized_start=734
  _globals['_EVE_OPAQUE_STATUS_ACTION']._serialized_end=787
  _globals['_ZINFOPATCHENVELOPE']._serialized_start=51
  _globals['_ZINFOPATCHENVELOPE']._serialized_end=206
  _globals['_ZINFOOPAQUEAPPINSTANCESTATUS']._serialized_start=209
  _globals['_ZINFOOPAQUEAPPINSTANCESTATUS']._serialized_end=368
  _globals['_ZINFOPATCHENVELOPEUSAGE']._serialized_start=370
  _globals['_ZINFOPATCHENVELOPEUSAGE']._serialized_end=487
  _globals['_ZINFOPATCHENVELOPEAPP']._serialized_start=489
  _globals['_ZINFOPATCHENVELOPEAPP']._serialized_end=568
# @@protoc_insertion_point(module_scope)
