# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/edge_node_cluster.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evecommon import acipherinfo_pb2 as evecommon_dot_acipherinfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63onfig/edge_node_cluster.proto\x12\x15org.lfedge.eve.config\x1a\x1b\x65vecommon/acipherinfo.proto\"\xe6\x01\n\x0f\x45\x64geNodeCluster\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12\x12\n\ncluster_id\x18\x02 \x01(\t\x12\x19\n\x11\x63luster_interface\x18\x03 \x01(\t\x12\x19\n\x11\x63luster_ip_prefix\x18\x04 \x01(\t\x12\x16\n\x0eis_worker_node\x18\x05 \x01(\x08\x12\x16\n\x0ejoin_server_ip\x18\x06 \x01(\t\x12\x43\n\x17\x65ncrypted_cluster_token\x18\x07 \x01(\x0b\x32\".org.lfedge.eve.common.CipherBlockB=\n\x15org.lfedge.eve.configZ$github.com/lf-edge/eve-api/go/configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config.edge_node_cluster_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025org.lfedge.eve.configZ$github.com/lf-edge/eve-api/go/config'
  _globals['_EDGENODECLUSTER']._serialized_start=87
  _globals['_EDGENODECLUSTER']._serialized_end=317
# @@protoc_insertion_point(module_scope)
